SELECT
    IFNULL(a.ADVANTAGE_CODE, -1) code,
    IFNULL(a.ADVANTAGE_DESCRIPTION, '-') description
FROM ( 
    SELECT bri_oid + 1000000 ADVANTAGE_CODE, bri_libelle ADVANTAGE_DESCRIPTION, 0 AS FATHER_CODE 
    FROM BRI_BON_REDUC_IMMEDIATE 
    WHERE BRI_LIBELLE is not NULL 
UNION ALL 
    SELECT LVI_OID + 2000000 ADVANTAGE_CODE, CONCAT('LV ', LVI_LIBELLE) ADVANTAGE_DESCRIPTION,
    0 AS FATHER_CODE 
    FROM LVI_LOT_VIRTUEL
    WHERE LVI_IRI_SCOPE = 1
UNION ALL
    SELECT AVA_OID + 3000000 ADVANTAGE_CODE, AVA_LIBELLE ADVANTAGE_DESCRIPTION, 0 AS FATHER_CODE 
    FROM AVA_AVANTAGE
    WHERE AVA_IRI_SCOPE = 1
UNION ALL 
    SELECT CAR_OID + 4000000 ADVANTAGE_CODE, CAR_LIBELLE ADVANTAGE_DESCRIPTION, 0 AS FATHER_CODE 
    FROM CAR_CARTE
    WHERE CAR_IRI_SCOPE = 1
UNION ALL 
    SELECT TEC_OID + 7000000 ADVANTAGE_CODE, concat('TECHNIQUE ', TEC_LIBELLE) ADVANTAGE_DESCRIPTION, 
    0 AS FATHER_CODE 
    FROM TEC_TECHNIQUE
    WHERE TEC_IRI_SCOPE = 1
) a
